version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: messanger-bridge-app
    restart: always
    depends_on:
      - redis
    volumes:
      - ./data:/data
      - ./messangers:/messangers
    command: ["poetry", "run", "app"]
  redis:
    image: redis:7.4.1-alpine
    container_name: messanger-bridge-redis
    restart: always
    ports:
      - "6479:6379"



volumes:
  data:
  messangers: